/* =========================================================
   ALVIN AI - MAIN JAVASCRIPT
   ========================================================= */

const $ = id => document.getElementById(id);

let currentUser = JSON.parse(localStorage.getItem("alvinUser")) || null;

let stats = JSON.parse(localStorage.getItem("alvinStats")) || {
  xp: 0,
  streak: 1,
  learned: 0,
  quizCorrect: 0,
  notes: 0
};

let notes = JSON.parse(localStorage.getItem("alvinNotes")) || [];

let quizIndex = 0;
let quizScore = 0;
let quizAnswered = false;

let flashIndex = 0;


/* =========================================================
   100 VOCABULARY WORDS
   ========================================================= */

const vocabulary = [
  ["Abundant","Existing in large quantities.","The company has abundant resources."],
  ["Accurate","Correct and exact.","Please provide accurate information."],
  ["Adapt","To change according to a situation.","We must adapt to change."],
  ["Ambitious","Having strong goals.","She is ambitious about her career."],
  ["Analyze","To examine carefully.","We need to analyze the data."],
  ["Approach","A way of dealing with something.","We need a new approach."],
  ["Assertive","Confident in expressing opinions.","He is an assertive speaker."],
  ["Authentic","Real or genuine.","This is an authentic example."],
  ["Benefit","An advantage or positive result.","Exercise has many benefits."],
  ["Brief","Short in duration or length.","Give me a brief explanation."],
  ["Capable","Having the ability to do something.","She is capable of leading the team."],
  ["Collaborate","To work together.","We collaborate on projects."],
  ["Commitment","A strong promise or dedication.","Success requires commitment."],
  ["Communicate","To share information or ideas.","Good leaders communicate clearly."],
  ["Compassion","Concern for others.","Compassion is important in leadership."],
  ["Confident","Feeling sure about yourself.","He is confident during interviews."],
  ["Consistent","Doing something regularly.","Be consistent with your practice."],
  ["Creative","Able to produce new ideas.","She has a creative mind."],
  ["Critical","Very important or involving careful judgment.","Critical thinking improves decisions."],
  ["Curious","Wanting to learn more.","Curious students learn quickly."],
  ["Decision","A choice made after thinking.","We made an important decision."],
  ["Dedication","Strong effort and commitment.","Her dedication is impressive."],
  ["Develop","To grow or improve.","Develop your communication skills."],
  ["Effective","Producing the desired result.","This is an effective strategy."],
  ["Efficient","Working well without wasting resources.","The process is efficient."],
  ["Encourage","To give confidence or support.","Teachers encourage students."],
  ["Essential","Absolutely necessary.","Communication is essential."],
  ["Evaluate","To judge the quality or value.","Managers evaluate performance."],
  ["Expand","To become larger.","The business plans to expand."],
  ["Flexible","Able to change easily.","Be flexible at work."],
  ["Focus","To concentrate on something.","Focus on your goals."],
  ["Generate","To produce something.","The project can generate revenue."],
  ["Growth","Development or increase.","The company achieved strong growth."],
  ["Identify","To recognize or find.","Identify the main problem."],
  ["Improve","To make something better.","Practice helps improve English."],
  ["Innovative","Introducing new ideas.","The company uses innovative technology."],
  ["Insight","A deep understanding.","The report provides useful insight."],
  ["Integrity","Honesty and strong moral principles.","Integrity builds trust."],
  ["Logical","Based on clear reasoning.","Use a logical approach."],
  ["Maintain","To keep something in good condition.","Maintain a positive attitude."],
  ["Motivate","To give someone a reason to act.","Good leaders motivate employees."],
  ["Objective","A goal or purpose.","Our objective is growth."],
  ["Opportunity","A favorable chance.","This is a great opportunity."],
  ["Optimize","To make something as effective as possible.","We need to optimize the process."],
  ["Perspective","A particular way of viewing something.","Consider another perspective."],
  ["Potential","Possible future ability or success.","She has great potential."],
  ["Precise","Exact and accurate.","Give a precise answer."],
  ["Prioritize","To decide what is most important.","Prioritize important tasks."],
  ["Proactive","Taking action before problems happen.","A proactive employee solves problems early."],
  ["Productive","Producing useful results.","Today was very productive."],
  ["Professional","Suitable for a workplace.","Use professional communication."],
  ["Progress","Movement toward improvement.","You are making progress."],
  ["Reliable","Able to be trusted.","He is a reliable employee."],
  ["Resilient","Able to recover from difficulties.","She is resilient after failure."],
  ["Resourceful","Good at solving problems.","He is a resourceful manager."],
  ["Relevant","Closely connected to the topic.","Give relevant examples."],
  ["Strategic","Related to long-term planning.","We need strategic thinking."],
  ["Sustainable","Able to continue for a long time.","The company needs sustainable growth."],
  ["Transparent","Open and easy to understand.","The company has a transparent policy."],
  ["Transform","To change significantly.","Technology can transform business."],
  ["Unique","One of a kind.","Every person has a unique skill."],
  ["Valuable","Worth a lot or useful.","Experience is valuable."],
  ["Versatile","Able to do many different things.","She is a versatile employee."],
  ["Vision","A picture of a desired future.","The leader has a clear vision."],
  ["Achieve","To successfully reach a goal.","Work hard to achieve your goals."],
  ["Acquire","To gain or obtain.","The company acquired another business."],
  ["Allocate","To distribute resources.","Managers allocate the budget."],
  ["Assess","To evaluate something.","Assess the investment risk."],
  ["Boost","To increase or improve.","Training can boost confidence."],
  ["Clarify","To make something clear.","Please clarify your point."],
  ["Competent","Having the necessary ability.","She is a competent analyst."],
  ["Contribute","To give or add something.","Everyone can contribute ideas."],
  ["Demonstrate","To show clearly.","Demonstrate your skills."],
  ["Diverse","Including different types of people or things.","We need a diverse team."],
  ["Enhance","To improve quality or value.","Education enhances career opportunities."],
  ["Estimate","To roughly calculate.","Estimate the project cost."],
  ["Facilitate","To make something easier.","Technology facilitates communication."],
  ["Forecast","To predict future events.","Analysts forecast market growth."],
  ["Implement","To put a plan into action.","The company implemented a new policy."],
  ["Influence","The power to affect something.","Advertising influences consumers."],
  ["Interpret","To explain the meaning of something.","Interpret the financial results."],
  ["Invest","To put money into something for future benefit.","People invest for long-term growth."],
  ["Manage","To control or organize.","Managers manage resources."],
  ["Negotiate","To discuss to reach an agreement.","We negotiated a better price."],
  ["Observe","To watch carefully.","Observe customer behavior."],
  ["Participate","To take part in something.","Students participate in discussions."],
  ["Predict","To say what may happen.","Experts predict economic growth."],
  ["Recommend","To suggest something.","I recommend regular practice."],
  ["Reduce","To make smaller or less.","Companies try to reduce costs."],
  ["Resolve","To solve a problem.","We need to resolve the issue."],
  ["Retain","To keep something.","Companies try to retain employees."],
  ["Significant","Important or noticeable.","There was significant growth."],
  ["Simplify","To make easier to understand.","Simplify the explanation."],
  ["Specialize","To focus on a specific area.","She specializes in finance."],
  ["Strengthen","To make stronger.","Training strengthens skills."],
  ["Succeed","To achieve the desired result.","Hard work helps you succeed."],
  ["Support","To help someone or something.","The team supports the project."],
  ["Target","A specific goal or group.","Our target market is young professionals."],
  ["Utilize","To use effectively.","Utilize your time wisely."],
  ["Verify","To check that something is correct.","Verify the information."],
  ["Withdraw","To take something back or remove.","The investor withdrew money."],
  ["Yield","The return produced by an investment.","The bond offers a good yield."]
];


/* =========================================================
   100 QUIZ QUESTIONS
   ========================================================= */

const quizData = [
  ["What is the opposite of 'increase'?",["Decrease","Improve","Expand","Grow"],0],
  ["What does 'accurate' mean?",["Correct","Fast","Large","Difficult"],0],
  ["Which word means 'to examine carefully'?",["Analyze","Avoid","Forget","Create"],0],
  ["What is NPV used for?",["Investment appraisal","Hiring","Marketing only","Payroll"],0],
  ["What does ROI stand for?",["Return on Investment","Rate of Income","Risk of Investment","Return of Interest"],0],
  ["Which market deals with new securities?",["Primary market","Secondary market","Money market","Retail market"],0],
  ["What is inflation?",["General rise in prices","Fall in employment","Increase in exports","Fall in prices"],0],
  ["What does communication mean?",["Sharing information","Saving money","Buying goods","Calculating tax"],0],
  ["Which is a soft skill?",["Communication","Accounting equation","NPV","Balance sheet"],0],
  ["What is a goal?",["A desired result","A problem","A loss","A document"],0],
  ["Which word means 'reliable'?",["Trustworthy","Weak","Unclear","Temporary"],0],
  ["What does MBA stand for?",["Master of Business Administration","Master of Banking Analysis","Management Business Account","Market Business Administration"],0],
  ["Which is a financial statement?",["Balance Sheet","Timetable","Resume","Agenda"],0],
  ["What does risk mean?",["Possibility of uncertain outcome","Guaranteed profit","Fixed salary","Tax"],0],
  ["What is capital budgeting?",["Evaluating long-term investments","Daily attendance","Recruitment","Advertising"],0],
  ["What is diversification?",["Spreading investments","Buying one stock","Avoiding investment","Taking loans"],0],
  ["Which is an example of an asset?",["Cash","Salary expense","Loan interest","Rent expense"],0],
  ["What is a liability?",["An obligation","A profit","An asset","Revenue"],0],
  ["What is revenue?",["Income from business activities","Expense","Loan","Tax"],0],
  ["What is profit?",["Revenue minus expenses","Expenses plus assets","Assets minus sales","Loans minus revenue"],0],
  ["Which word means 'improve'?",["Enhance","Reduce","Withdraw","Ignore"],0],
  ["What does proactive mean?",["Taking action early","Waiting always","Avoiding work","Ignoring problems"],0],
  ["Which skill is useful in interviews?",["Communication","Silence","Avoiding questions","Late arrival"],0],
  ["What is a budget?",["Financial plan","Loan document","Resume","Contract"],0],
  ["What is saving?",["Setting aside money","Spending everything","Borrowing","Investing only"],0],
  ["What is investment?",["Putting resources into something for future benefit","Spending without planning","Borrowing money","Paying tax"],0],
  ["What is a stock?",["Ownership share in a company","Company loan","Salary","Expense"],0],
  ["What is a bond?",["Debt instrument","Ownership share","Salary","Tax"],0],
  ["What is liquidity?",["Ease of converting to cash","Profitability only","Debt level","Market size"],0],
  ["What is an interest rate?",["Cost of borrowing money","Tax rate","Salary rate","Profit margin"],0],
  ["What is financial management?",["Managing financial resources","Managing attendance","Recruiting staff","Designing products"],0],
  ["What does 'allocate' mean?",["Distribute resources","Destroy resources","Borrow resources","Ignore resources"],0],
  ["Which is an example of fixed cost?",["Rent","Raw material per unit","Sales commission","Packaging per unit"],0],
  ["What is break-even point?",["Where total revenue equals total cost","Maximum profit","Minimum sales","Total assets"],0],
  ["What is SWOT?",["Strengths Weaknesses Opportunities Threats","Sales Work Operations Tax","Strategy Work Organization Technology","Stock Wealth Opportunity Trade"],0],
  ["What is a strength?",["Internal positive factor","External threat","External opportunity","Tax"],0],
  ["What is an opportunity?",["External favorable factor","Internal weakness","Expense","Debt"],0],
  ["What is behavioural finance?",["Study of psychology in financial decisions","Bank accounting","Tax calculation","Payroll"],0],
  ["What can influence behavioural investors?",["Emotions and biases","Only formulas","Only laws","Only salaries"],0],
  ["What is overconfidence?",["Excessive belief in one's ability","Fear of loss","Saving money","Diversification"],0],
  ["What is diversification useful for?",["Reducing unsystematic risk","Increasing one-stock risk","Avoiding all losses","Guaranteeing profit"],0],
  ["What is a portfolio?",["Collection of investments","Single loan","Salary slip","Tax form"],0],
  ["What is a financial market?",["Market where financial assets are traded","Grocery market","Job market only","Housing only"],0],
  ["What is a stock exchange?",["Organized securities marketplace","Bank account","Tax office","Insurance office"],0],
  ["What is SEBI?",["Indian securities market regulator","Indian tax department","Central bank","Insurance company"],0],
  ["What is RBI?",["India's central bank","Stock exchange","Insurance regulator","Tax authority"],0],
  ["What does GST relate to?",["Goods and Services Tax","Government Salary Transfer","General Sales Trade","Growth Service Tax"],0],
  ["What is an entrepreneur?",["Person who starts or manages a business venture","Employee only","Customer","Auditor"],0],
  ["What is leadership?",["Ability to guide and influence others","Avoiding responsibility","Only giving orders","Working alone"],0],
  ["What is teamwork?",["Working together toward a goal","Competing always","Working alone","Avoiding communication"],0],
  ["What is time management?",["Planning and controlling time","Working without breaks","Ignoring deadlines","Doing everything randomly"],0],
  ["What is productivity?",["Useful output relative to resources","Salary only","Attendance","Office size"],0],
  ["What is innovation?",["Introducing useful new ideas","Copying everything","Avoiding change","Reducing quality"],0],
  ["What is strategy?",["Long-term plan to achieve goals","Daily expense","Salary","Tax"],0],
  ["What is a target market?",["Specific customer group","Company employees only","Government only","Suppliers only"],0],
  ["What is marketing?",["Creating and delivering value to customers","Accounting only","Recruitment only","Tax filing"],0],
  ["What is customer satisfaction?",["How well customer expectations are met","Company profit only","Employee salary","Tax payment"],0],
  ["What is demand?",["Quantity consumers are willing to buy","Company supply only","Profit only","Tax"],0],
  ["What is supply?",["Quantity producers offer","Consumer demand only","Salary","Profit"],0],
  ["What is GDP?",["Value of goods and services produced in an economy","Government debt only","Bank profit","Tax revenue"],0],
  ["What is unemployment?",["People willing and able to work but without jobs","People working overtime","Students only","Retired people only"],0],
  ["What is economic growth?",["Increase in economic output","Fall in production","Increase in unemployment only","Fall in income"],0],
  ["What is a recession?",["Significant decline in economic activity","Rapid growth","High employment","Market expansion"],0],
  ["What is a budget deficit?",["Expenses exceed revenue","Revenue exceeds expenses","No expenses","No revenue"],0],
  ["What is a surplus?",["Revenue exceeds expenses","Expenses exceed revenue","Debt only","Loss"],0],
  ["What is credit?",["Ability to borrow with repayment obligation","Cash gift","Profit","Tax"],0],
  ["What is a loan?",["Borrowed money to be repaid","Investment return","Salary","Asset only"],0],
  ["What is collateral?",["Asset pledged to secure a loan","Salary","Profit","Tax"],0],
  ["What is insurance?",["Protection against specified risks","Guaranteed profit","Loan","Investment only"],0],
  ["What is a premium?",["Amount paid for insurance coverage","Loan principal","Profit","Tax"],0],
  ["What is a mutual fund?",["Pooled investment vehicle","Bank loan","Insurance policy","Tax"],0],
  ["What is NAV?",["Net Asset Value","New Account Value","National Asset Verification","Net Annual Volume"],0],
  ["What is an index?",["Measure representing a group of securities","Single company only","Loan document","Tax"],0],
  ["What is Sensex?",["BSE benchmark index","Bank loan","Insurance index","Tax index"],0],
  ["What is Nifty 50?",["NSE benchmark index","BSE bond","Bank index only","Insurance scheme"],0],
  ["What is a dividend?",["Distribution of company profit to shareholders","Loan payment","Tax refund","Salary"],0],
  ["What is market capitalization?",["Value of a company's outstanding shares","Annual salary","Total expenses","Loan amount"],0],
  ["What is P/E ratio?",["Price-to-Earnings ratio","Profit-to-Expense ratio","Price-to-Equity only","Payment-to-Earnings"],0],
  ["What is a bull market?",["Market with generally rising prices","Falling market","Closed market","No trading"],0],
  ["What is a bear market?",["Market with generally falling prices","Rising market","Closed market","No investment"],0],
  ["What is volatility?",["Degree of price fluctuation","Fixed return","Tax rate","Salary growth"],0],
  ["What is a derivative?",["Financial contract whose value derives from an underlying asset","Bank account","Salary","Tax"],0],
  ["What is a forward contract?",["Agreement to transact in future at agreed terms","Immediate cash sale only","Insurance policy","Equity share"],0],
  ["What is a futures contract?",["Standardized exchange-traded agreement","Salary contract","Loan only","Insurance only"],0],
  ["What is an option?",["Right but not obligation to buy or sell","Mandatory purchase","Loan","Tax"],0],
  ["What is a call option?",["Right to buy","Right to sell","Mandatory sale","Loan"],0],
  ["What is a put option?",["Right to sell","Right to buy","Mandatory purchase","Dividend"],0],
  ["What is hedging?",["Reducing risk using financial strategies","Increasing risk intentionally","Avoiding accounting","Increasing taxes"],0],
  ["What is arbitrage?",["Seeking profit from price differences","Long-term saving only","Tax planning","Budgeting"],0],
  ["What is WACC?",["Weighted Average Cost of Capital","Working Asset Capital Cost","Weighted Annual Cash Cost","Working Average Credit Capital"],0],
  ["What is cost of capital?",["Required return/cost associated with financing","Salary","Tax only","Revenue"],0],
  ["What is debt financing?",["Raising funds through borrowing","Selling ownership only","Saving cash","Reducing assets"],0],
  ["What is equity financing?",["Raising funds by selling ownership","Borrowing only","Tax payment","Expense"],0],
  ["What is leverage?",["Use of fixed costs or debt to magnify returns and risk","Saving money","Diversification only","Insurance"],0],
  ["What is cash flow?",["Movement of cash into and out of a business","Profit only","Revenue only","Asset value"],0],
  ["What is working capital?",["Current assets minus current liabilities","Fixed assets minus debt","Revenue minus tax","Profit minus salary"],0],
  ["What is a current asset?",["Asset expected to convert to cash/use within short term","Long-term building only","Lon
